# action.yml
name: 'Mutex Action'
branding:
  icon: 'lock'
  color: 'black'
description: 'A simple locking/unlocking mechanism to provide mutual exclusion in Github Actions'
inputs:
  repo-token:
    description: 'The token for accessing the repo.'
    required: false
    default: ${{ github.token }}
  github_server:
    description: 'The GitHub server URL without `https`. This might be useful for e.g. GHES'
    required: false
    default: github.com
  repository:
    description: 'The repository path that stores the lock. E.g `ben-z/gh-action-mutex`'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'The branch to use for the mutex'
    required: false
    default: 'gh-mutex'
  debug:
    description: 'Print debug output'
    required: false
    default: "false"
  internal_checkout-location:
    description: '[Internal] The location to store the mutex repo'
    required: false
    default: '/run/gh-action-mutex/repo'
  action:
    description: 'What locking action to take, either `lock` or `unlock`'
    required: false
    default: 'lock'
  ticket_id:
    description: 'If action is unlock, this is the ticket id from a prior lock'
    required: false
outputs:
  ticket_id:
    description: 'The unique ID of this particular lock, can be used to forcibly unlock in a subsequent action call'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ARG_BRANCH: ${{ inputs.branch }}
    ARG_CHECKOUT_LOCATION: ${{ inputs.internal_checkout-location }}
    ARG_GITHUB_SERVER: ${{ inputs.github_server }}
    ARG_REPOSITORY: ${{ inputs.repository }}
    ARG_REPO_TOKEN: ${{ inputs.repo-token }}
    ARG_DEBUG: ${{ inputs.debug }}
    ARG_ACTION: ${{ inputs.action }}
    ARG_TICKET_ID: ${{ inputs.ticket_id }}
  entrypoint: '/scripts/lock.sh'
  post-entrypoint: '/scripts/unlock.sh'
